{
 "title": "Nebula Network",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Mean encryption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheusns_nebula_messages_encrypt{type=\"mean\"}"
    },
    {}
   ]
  },
  {
   "title": "Mean decryption time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "prometheusns_nebula_messages_decrypt{type=\"mean\"}"
    }
   ]
  },
  {
   "title": "Packet processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheusns_nebula_messages_process{type=\"mean\"}"
    },
    {}
   ]
  },
  {
   "title": "Pending Paths",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheusns_nebula_cache_paths_pending_active"
    },
    {}
   ]
  },
  {
   "title": "Path establishment ACK",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheusns_nebula_messages_rx_ack_path"
    },
    {
     "expr": "prometheusns_nebula_messages_tx_ack_path"
    },
    {}
   ]
  },
  {
   "title": "Duplicate Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheusns_nebula_cache_packets_duplicate"
    },
    {},
    {}
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Packets in cache ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheusns_nebula_cache_packets_active"
    },
    {}
   ]
  },
  {
   "title": "Packets Flushed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheusns_nebula_cache_packets_flushed"
    },
    {}
   ]
  }
 ]
}