global:
  scrape_interval:     1s
  evaluation_interval: 5s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['10.0.10.5:8080', '10.0.10.6:8080', '10.0.10.7:8080', '10.0.10.8:8080']