global:
  scrape_interval:     1s
  evaluation_interval: 5s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['172.20.0.3:8080', '172.20.0.4:8080', '172.20.0.5:8080', '172.20.0.6:8080']